services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8888:8080"
    environment:
      - DOZZLE_LEVEL=info
      # - DOZZLE_USERNAME=admin
      # - DOZZLE_PASSWORD=password
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.101.0
    ports:
      - "8428:8428"
    volumes:
      - vmdata:/storage
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--storageDataPath=/storage"
    restart: always

  # Visualization Tool (~2Gb)
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3003:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - ./grafana_data:/var/lib/grafana

  # This with show metrics of Docker Containers as well in Grafana
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:v0.47.2
  #   container_name: cadvisor
  #   restart: unless-stopped
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   ports:
  #     - "8081:8080"
  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      SHEMA: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: my_database
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:secret_password@db:5432/my_database}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # PGAdmin Panel
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5050:80"
    depends_on:
      - db
  # Backend (Node.js)
  backend:
    build: ./backend
    container_name: node_backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search: .
    volumes:
      - ./backend:/app # maps local code to the container
      - /app/node_modules # this will keep modules inside the container
    restart: always
    ports:
      - "${NODE_PORT}:5000"
    env_file:
      - ./backend/.env
    environment:
      - SCHEMA=app
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:secret_password@db:5432/my_database}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
    command: >
      sh -c "
        ./wait-for-test-db.sh &&
        npm run dev
      "
    #  sh -c "npm run migrate:up --schema app && npm run dev"
  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search: .
    ports:
      - "${REACT_PORT}:3000"
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

volumes:
  pgdata:
  # grafana_data:
  prometheus:
  vmdata:
