services:
  app_test:
    image: my-app-test:latest
    build: ./backend
    env_file:
      - ./backend/.env.test
    container_name: node_backend_test
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search: .
    environment:
      - NODE_ENV=test
      - SCHEMA=app
      - TEST_COMMAND=${TEST_COMMAND:-test:ci}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:test_secret_password@postgres_test:5432/test_my_database}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres_test:
        condition: service_healthy
    # Wait for database before running tests
    command: >
      sh -c "
        ./wait-for-test-db.sh &&
        npm run ${TEST_COMMAND:-test:ci}
      "
    networks:
      - test_network
  postgres_test:
    image: postgres:15-alpine
    env_file:
      - ./backend/.env.test
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL:-postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_CONNECTION}:5432/${DB_NAME}}

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5433:5432" # External host port mapped to internal Postgres port
    tmpfs:
      - /var/lib/postgresql/data
    volumes: []
    # - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_my_database"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
