services:
  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # PGAdmin Panel
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5050:80"
    depends_on:
      - db
  # Backend (Node.js)
  backend:
    build: ./backend
    container_name: node_backend
    volumes:
      - ./backend:/app # maps local code to the container
      - /app/node_modules # this will keep modules inside the container
    restart: always
    ports:
      - "${NODE_PORT}:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
    command: sh -c "npm run migrate && npm run dev"
  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "${REACT_PORT}:3000"
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

volumes:
  pgdata:
