### Get all users
GET http://localhost:5000/users

### Create new user
POST http://localhost:5000/users
Content-Type: application/json

{
  "username": "tes11",
  "email": "test22211@tes.tt",
  "password": "some_secret_password",
  "age": 18,
  "is_active": true
}