### Get all users
GET http://localhost:5000/api/v1/users
Authorization: Bearer {{accessToken}}

### Search users
GET http://localhost:5000/api/v1/users?createdAt=2026-04-29


### Create new user
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "username": "boom2",
  "email": "boom@tt.tt",
  "password": "some_secret_password",
  "age": 18,
  "is_active": false
}

### Update user by id
PUT http://localhost:5000/api/v1/users/2
Content-Type: application/json

{
  "username": "test2",
  "email":"invalidemail@test.tt"
}

### Get user by id
GET http://localhost:5000/api/v1/users/1

### Update user password by id
PATCH http://localhost:5000/api/v1/users/4/password
Content-Type: application/json

{
  "old_password":"some_secret_password",
  "new_password": "some_password",
  "confirm_password": "some_password"
}

### Delete user by id
DELETE http://localhost:5000/api/v1/users/1

### Activate user by id
PATCH http://localhost:5000/api/v1/users/2/activate


### Register new user
POST http://localhost:5000/api/v1/users/register
Content-Type: application/json

{
  "username":"sos",
  "email": "sos@sos.com",
  "password": "password",
  "confirm_password": "password"
}

### Login user
# @name login
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "sos@sos.com",
  "password": "password"
}

###

@accessToken = {{login.response.body.data.accessToken}}

### Logout user
POST http://localhost:5000/api/v1/auth/logout

### Logout from all sessions
POST http://localhost:5000/api/v1/users/10/logout

### Refresh token
POST http://localhost:5000/api/v1/auth/refresh


### Get metrics
GET http://localhost:5000/api/v1/metrics

### Get all valid tokens for user
GET http://localhost:5000/api/v1/users/1/tokens

### Revoke token by id
DELETE http://localhost:5000/api/v1/tokens/42b4a934-bfef-4f06-b6dd-04045b56afaa
