### Get all users
GET http://localhost:5000/users

### Create new user
POST http://localhost:5000/users
Content-Type: application/json

{
  "username": "tes112ww",
  "email": "test2w22211@tt.tt",
  "password": "some_secret_password",
  "age": 18,
  "is_active": false
}

### Update user by id
PUT http://localhost:5000/users/1
Content-Type: application/json

{
  "username": "newUsername",
  "email":"test@test.tt"
}

### Update user password by id
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
  "old_password":"some_secret_password",
  "new_password": "some_password",
  "confirm_password": "some_password"
}

