# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 3

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      SCHEMA: app
      DATABASE_URL: postgresql://postgres:secret_password@localhost:5432/test_db?options=-csearch_path=app,public
      DB_USERNAME: postgres
      DB_PASSWORD: secret_password
      DB_NAME: my_database
      DB_PORT: 5432
    services: # База поднимается один раз для всех тестов
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npm run migrate:ci

      # - name: Run Unit Tests
      #   run: npm run test:unit

      - name: Integration Tests
        run: npm run test:integration

      - name: E2E Tests
        run: npm run test:e2e
        env:
          JWT_SECRET: some_secret_hash_string
          JWT_EXPIRES_IN: "1d"
          JWT_ACCESS_TOKEN_SECRET: super-secret-access-key-minimum-32-character
          JWT_REFRESH_TOKEN_SECRET: super-secret-refresh-key-minimum-32-character
          JWT_ACCESS_TOKEN_EXPIRES_IN: "1h"
          JWT_REFRESH_TOKEN_EXPIRES_IN: "7d"
